contains(light_salmon,[[5,dotted_olive],[4,wavy_lavender]]).
contains(dark_purple,[[5,striped_maroon],[1,wavy_maroon]]).
contains(muted_lime,[[4,drab_lavender],[1,clear_orange],[2,striped_black]]).
contains(light_green,[[5,dull_gray],[3,dark_crimson]]).
contains(bright_violet,[[1,bright_purple]]).
contains(dotted_magenta,[[2,wavy_beige],[1,dotted_bronze]]).
contains(wavy_bronze,[[4,clear_fuchsia]]).
contains(bright_plum,[[2,dim_violet]]).
contains(shiny_yellow,[[5,clear_violet],[3,drab_maroon]]).
contains(pale_tomato,[[3,bright_aqua]]).
contains(light_chartreuse,[[3,vibrant_fuchsia]]).
contains(mirrored_blue,[[2,pale_aqua]]).
contains(muted_maroon,[[3,muted_indigo],[1,vibrant_gold]]).
contains(clear_green,[[4,dotted_beige]]).
contains(muted_indigo,[[1,dull_green]]).
contains(faded_orange,[[1,shiny_gold],[4,dim_tomato]]).
contains(posh_purple,[[3,posh_turquoise],[4,dull_lime],[3,vibrant_fuchsia],[2,dull_green]]).
contains(dim_beige,[[4,dull_fuchsia],[5,pale_silver],[3,shiny_silver]]).
contains(dark_tomato,[[5,dotted_magenta]]).
contains(muted_chartreuse,[[2,plaid_chartreuse],[3,faded_orange]]).
contains(drab_teal,[[2,dotted_blue],[2,striped_maroon],[5,dotted_tomato],[5,striped_gold]]).
contains(shiny_olive,[[5,dim_blue],[3,dotted_violet]]).
contains(bright_magenta,[[2,dotted_silver],[4,plaid_black],[4,posh_tomato],[4,dark_salmon]]).
contains(striped_crimson,[[3,muted_tomato],[2,mirrored_black],[2,wavy_yellow],[2,faded_green]]).
contains(shiny_bronze,[[5,striped_turquoise],[5,light_coral],[4,striped_aqua],[5,dim_bronze]]).
contains(striped_gray,[[2,faded_coral]]).
contains(striped_yellow,[[4,clear_chartreuse],[2,shiny_violet],[2,faded_gold]]).
contains(clear_tan,[[4,dim_green],[3,dull_white],[2,posh_turquoise]]).
contains(dark_bronze,[[1,shiny_purple],[2,dark_coral],[5,plaid_gold]]).
contains(light_orange,[[3,clear_green],[2,muted_blue],[3,drab_gray]]).
contains(wavy_turquoise,[[3,clear_gold],[5,wavy_tomato],[5,dotted_coral]]).
contains(drab_tan,[[1,striped_lime],[1,clear_orange],[3,pale_white],[3,bright_yellow]]).
contains(dark_plum,[[2,striped_blue],[4,bright_fuchsia]]).
contains(dotted_blue,[[2,pale_aqua],[1,dotted_orange],[4,dotted_indigo],[1,plaid_blue]]).
contains(light_white,[[5,dull_red],[4,faded_salmon]]).
contains(posh_olive,[[4,shiny_silver],[5,dark_bronze]]).
contains(dull_olive,[[4,dark_plum],[2,dotted_coral],[4,clear_blue],[2,dull_maroon]]).
contains(dim_tomato,[[2,dim_chartreuse],[3,shiny_gold]]).
contains(clear_lavender,[[5,light_aqua],[5,dull_tan]]).
contains(wavy_teal,[[4,dotted_beige]]).
contains(mirrored_orange,[[2,pale_beige]]).
contains(dim_purple,[[2,striped_gold]]).
contains(dark_chartreuse,[[2,wavy_tomato]]).
contains(bright_coral,[[4,muted_violet]]).
contains(drab_yellow,[[1,dark_gold],[5,dotted_gold],[3,mirrored_chartreuse]]).
contains(clear_orange,[[3,bright_cyan],[1,dull_lavender]]).
contains(bright_brown,[[1,light_teal],[4,dotted_salmon]]).
contains(drab_violet,[[5,bright_crimson],[2,wavy_bronze],[1,wavy_lavender]]).
contains(dull_turquoise,[[3,vibrant_tomato],[4,light_indigo],[4,shiny_green]]).
contains(muted_cyan,[[5,muted_plum],[3,drab_red],[5,mirrored_plum]]).
contains(pale_indigo,[[4,dim_yellow],[1,bright_red]]).
contains(vibrant_green,[[3,shiny_white],[3,faded_fuchsia],[4,clear_orange]]).
contains(dotted_crimson,[[5,clear_fuchsia],[1,clear_tan]]).
contains(drab_maroon,[[4,muted_olive]]).
contains(dull_bronze,[[5,shiny_indigo],[2,dim_chartreuse]]).
contains(wavy_brown,[[1,bright_teal]]).
contains(posh_blue,[[3,striped_blue],[3,drab_teal],[5,shiny_black]]).
contains(clear_chartreuse,[[1,clear_tan],[2,dim_cyan],[1,drab_lime]]).
contains(faded_coral,[[4,dotted_green],[3,plaid_cyan],[2,bright_cyan]]).
contains(dotted_green,[[4,drab_gray]]).
contains(wavy_orange,[[5,striped_coral],[5,striped_blue],[5,wavy_green]]).
contains(dotted_tomato,[[1,light_crimson],[5,light_lime],[3,vibrant_purple],[5,clear_plum]]).
contains(pale_fuchsia,[[2,muted_orange],[3,dull_orange],[4,posh_bronze],[2,faded_purple]]).
contains(wavy_lavender,[[1,dull_lime]]).
contains(dull_blue,[[5,striped_silver],[5,bright_brown],[5,dotted_green],[3,dark_brown]]).
contains(muted_beige,[[5,dim_tomato],[2,shiny_purple]]).
contains(pale_lime,[[1,vibrant_crimson],[1,pale_plum],[4,mirrored_gold],[3,bright_chartreuse]]).
contains(mirrored_plum,[[2,dim_white],[3,posh_cyan],[3,dark_lime]]).
contains(light_coral,[[4,clear_silver],[5,dim_green],[1,striped_tomato]]).
contains(faded_lavender,[[2,dark_tan],[2,wavy_tomato],[2,light_coral],[5,dotted_silver]]).
contains(plaid_lime,[[3,light_orange],[5,drab_black],[2,drab_lime]]).
contains(vibrant_cyan,[[1,vibrant_gray],[5,wavy_teal]]).
contains(dark_blue,[[5,clear_tan],[5,clear_silver],[3,drab_black]]).
contains(plaid_coral,[[2,plaid_aqua],[3,drab_gold],[5,mirrored_plum],[2,dim_bronze]]).
contains(light_maroon,[[3,dim_yellow],[1,light_red]]).
contains(plaid_silver,[[1,pale_maroon],[5,shiny_black],[2,dark_coral],[3,posh_violet]]).
contains(clear_violet,[[2,vibrant_fuchsia]]).
contains(clear_cyan,[[2,plaid_yellow],[4,plaid_olive],[5,dull_green]]).
contains(dim_magenta,[[1,wavy_plum]]).
contains(drab_salmon,[[5,dull_white],[4,dark_brown]]).
contains(pale_magenta,[[1,muted_olive],[5,mirrored_fuchsia],[3,shiny_purple]]).
contains(drab_coral,[[2,striped_silver]]).
contains(light_gold,[[4,shiny_aqua],[5,dim_violet],[2,dotted_orange]]).
contains(shiny_cyan,[[4,muted_aqua],[3,striped_maroon],[5,light_salmon]]).
contains(drab_beige,[[4,light_gold],[5,dull_white]]).
contains(plaid_fuchsia,[]).
contains(vibrant_teal,[[4,muted_maroon],[5,posh_violet],[2,clear_tan],[1,dull_orange]]).
contains(dim_cyan,[[1,dark_turquoise]]).
contains(mirrored_chartreuse,[[1,dull_lavender],[4,pale_red],[4,plaid_chartreuse]]).
contains(plaid_gold,[[5,dark_turquoise],[4,dim_turquoise],[4,plaid_fuchsia]]).
contains(wavy_gold,[[2,light_lime],[5,wavy_tomato]]).
contains(wavy_red,[[4,dotted_lavender],[3,dotted_blue],[4,striped_brown],[2,faded_orange]]).
contains(dull_red,[[5,drab_green]]).
contains(light_red,[[2,dark_coral]]).
contains(wavy_crimson,[[2,shiny_gold],[1,drab_white]]).
contains(drab_turquoise,[[4,posh_gold],[2,pale_plum],[3,wavy_beige],[2,drab_beige]]).
contains(dim_lavender,[[4,dark_olive]]).
contains(shiny_tan,[[1,shiny_teal],[1,clear_tan],[4,wavy_beige],[5,posh_coral]]).
contains(mirrored_fuchsia,[[3,bright_brown]]).
contains(clear_white,[[2,bright_cyan],[1,pale_orange],[3,vibrant_gold],[3,dim_cyan]]).
contains(clear_magenta,[[3,dull_violet],[2,dull_coral],[1,dull_olive],[1,pale_cyan]]).
contains(mirrored_salmon,[[5,drab_gray],[1,striped_magenta]]).
contains(vibrant_crimson,[[4,shiny_aqua],[5,faded_bronze]]).
contains(clear_yellow,[[3,bright_beige]]).
contains(striped_olive,[[2,clear_silver],[5,dim_orange],[2,posh_black],[2,striped_lavender]]).
contains(pale_olive,[[3,dotted_blue],[2,faded_indigo],[3,pale_crimson],[4,clear_tan]]).
contains(striped_white,[[2,drab_silver],[2,clear_brown]]).
contains(dotted_chartreuse,[[4,dark_brown],[4,dim_maroon],[3,plaid_chartreuse],[2,dark_red]]).
contains(dim_fuchsia,[[3,posh_indigo],[5,clear_purple]]).
contains(shiny_lime,[[3,muted_gold],[3,vibrant_crimson],[3,mirrored_green]]).
contains(striped_blue,[[2,clear_coral],[4,drab_green],[2,dull_green]]).
contains(shiny_beige,[[3,wavy_lime]]).
contains(dim_tan,[[2,clear_green],[2,dull_green]]).
contains(posh_cyan,[[4,faded_purple]]).
contains(striped_violet,[[2,faded_orange],[5,plaid_crimson],[2,dull_fuchsia],[2,bright_black]]).
contains(mirrored_crimson,[[1,drab_gray],[3,faded_crimson],[2,dim_white],[4,dull_green]]).
contains(dim_orange,[[4,dim_lime],[1,drab_black]]).
contains(drab_cyan,[[2,shiny_salmon],[4,muted_plum],[4,dotted_lavender],[2,plaid_gray]]).
contains(drab_brown,[[2,muted_purple]]).
contains(mirrored_white,[[4,mirrored_crimson],[5,pale_plum],[2,bright_maroon]]).
contains(vibrant_silver,[[3,dark_bronze],[2,light_olive],[3,posh_cyan]]).
contains(wavy_magenta,[[3,muted_aqua],[3,clear_beige],[5,drab_beige],[1,faded_teal]]).
contains(striped_purple,[[3,pale_crimson],[1,bright_maroon],[2,striped_bronze],[4,pale_gold]]).
contains(dark_teal,[[4,shiny_aqua],[1,dull_white],[2,dotted_orange],[2,dull_green]]).
contains(dotted_coral,[[5,dark_turquoise]]).
contains(vibrant_lime,[[3,dim_purple],[5,shiny_black],[3,dotted_black],[1,mirrored_coral]]).
contains(bright_gold,[[3,posh_tan],[4,drab_gray],[1,dotted_maroon],[2,clear_fuchsia]]).
contains(dark_fuchsia,[[2,dull_yellow],[1,dim_orange],[4,muted_beige]]).
contains(muted_tomato,[[1,posh_teal],[5,shiny_olive]]).
contains(dull_indigo,[[4,muted_maroon]]).
contains(bright_purple,[[1,dotted_olive],[1,wavy_chartreuse],[1,clear_tan],[2,dotted_green]]).
contains(wavy_violet,[[3,striped_silver],[1,pale_plum]]).
contains(shiny_orange,[[2,drab_black],[3,drab_lime],[2,shiny_black],[4,faded_purple]]).
contains(light_beige,[[5,dim_coral],[1,dark_white],[1,light_crimson],[3,mirrored_coral]]).
contains(drab_tomato,[[5,shiny_teal],[2,drab_beige],[2,shiny_purple]]).
contains(drab_lavender,[[3,striped_tomato],[1,bright_brown]]).
contains(shiny_plum,[[4,plaid_magenta],[5,posh_indigo],[1,wavy_violet],[5,clear_white]]).
contains(dotted_brown,[[3,mirrored_olive],[5,light_yellow],[3,light_tomato]]).
contains(wavy_coral,[[2,mirrored_plum],[4,posh_purple]]).
contains(shiny_maroon,[[4,muted_cyan],[1,wavy_blue],[2,clear_lime],[3,plaid_orange]]).
contains(posh_bronze,[[1,plaid_gold],[1,posh_yellow],[4,wavy_lime],[2,dull_white]]).
contains(bright_fuchsia,[[3,dull_silver],[2,light_lime]]).
contains(dull_plum,[[1,dotted_salmon],[4,shiny_lavender],[5,mirrored_purple],[2,bright_cyan]]).
contains(bright_aqua,[[5,dull_salmon],[1,plaid_crimson],[4,shiny_tomato],[5,vibrant_fuchsia]]).
contains(shiny_salmon,[[4,plaid_orange],[5,drab_green]]).
contains(muted_coral,[[4,dull_indigo],[4,pale_plum],[5,dotted_black]]).
contains(vibrant_salmon,[[5,dark_turquoise],[1,drab_red]]).
contains(dull_black,[[1,dull_magenta]]).
contains(plaid_white,[[3,shiny_purple]]).
contains(drab_green,[[5,striped_maroon],[4,dark_crimson],[1,faded_teal],[1,dull_green]]).
contains(faded_purple,[[4,shiny_gold]]).
contains(striped_lime,[[5,striped_turquoise],[1,clear_silver]]).
contains(clear_black,[[4,dark_beige],[3,posh_black]]).
contains(vibrant_purple,[[5,dark_brown]]).
contains(clear_beige,[[1,light_teal],[4,plaid_fuchsia]]).
contains(light_lime,[[4,drab_gray],[1,dark_white],[3,drab_tomato],[2,plaid_maroon]]).
contains(muted_violet,[[1,posh_turquoise],[4,mirrored_white]]).
contains(vibrant_olive,[[3,clear_beige]]).
contains(bright_salmon,[[1,plaid_orange]]).
contains(drab_bronze,[[4,shiny_turquoise],[1,clear_fuchsia]]).
contains(drab_plum,[[2,muted_gold],[5,mirrored_turquoise],[5,faded_orange],[5,bright_magenta]]).
contains(dotted_turquoise,[[5,striped_maroon],[3,mirrored_violet],[1,dark_fuchsia]]).
contains(wavy_olive,[[5,vibrant_maroon],[3,shiny_tan],[5,vibrant_yellow],[5,dotted_silver]]).
contains(wavy_tomato,[[1,pale_white],[5,light_yellow]]).
contains(plaid_chartreuse,[[3,drab_black]]).
contains(pale_chartreuse,[[3,muted_purple],[1,dull_green],[3,dark_brown],[5,light_teal]]).
contains(dotted_cyan,[[2,pale_salmon]]).
contains(muted_gold,[[5,plaid_silver],[5,dotted_orange]]).
contains(posh_orange,[[5,posh_purple],[4,dark_teal],[4,dotted_silver]]).
contains(pale_brown,[[2,faded_teal]]).
contains(wavy_aqua,[[5,muted_plum],[5,wavy_tomato],[3,mirrored_gold],[5,drab_tan]]).
contains(bright_blue,[[2,clear_green]]).
contains(dotted_red,[[4,wavy_plum],[5,muted_green]]).
contains(clear_tomato,[[3,bright_cyan],[1,dull_gray],[5,drab_maroon],[4,muted_indigo]]).
contains(plaid_orange,[[4,dotted_coral],[5,pale_gray],[5,shiny_violet],[2,pale_aqua]]).
contains(muted_teal,[[2,muted_maroon],[1,drab_teal],[2,light_teal]]).
contains(wavy_blue,[[5,pale_chartreuse],[2,shiny_white],[5,posh_teal]]).
contains(posh_teal,[[3,pale_chartreuse]]).
contains(mirrored_magenta,[[1,bright_aqua]]).
contains(vibrant_orange,[[3,mirrored_magenta],[1,mirrored_violet],[3,posh_indigo],[5,faded_orange]]).
contains(posh_black,[[5,bright_red]]).
contains(pale_white,[[3,dark_teal],[1,dotted_silver],[2,clear_green]]).
contains(posh_tomato,[[1,shiny_yellow],[3,light_black],[2,drab_blue],[5,wavy_crimson]]).
contains(mirrored_teal,[[1,drab_gray],[4,light_lime]]).
contains(muted_green,[[5,striped_brown]]).
contains(dim_gold,[[2,posh_indigo],[5,clear_indigo],[4,posh_gray]]).
contains(dull_gray,[[4,posh_orange],[3,shiny_gold],[1,dim_tomato],[3,bright_crimson]]).
contains(striped_green,[[4,dark_tan],[2,drab_gray],[1,mirrored_brown]]).
contains(clear_coral,[[2,striped_brown],[2,light_lime]]).
contains(posh_brown,[[3,vibrant_purple],[3,dark_chartreuse],[5,shiny_cyan]]).
contains(dotted_black,[[2,bright_crimson],[3,posh_orange],[4,light_gold],[5,dark_brown]]).
contains(posh_chartreuse,[[5,wavy_salmon],[3,striped_silver],[2,drab_violet]]).
contains(mirrored_tomato,[[3,pale_crimson]]).
contains(bright_yellow,[[1,shiny_coral],[2,muted_blue],[4,wavy_beige]]).
contains(dull_salmon,[[3,bright_blue],[4,dull_green],[5,drab_salmon]]).
contains(pale_black,[[5,shiny_salmon]]).
contains(drab_aqua,[[5,striped_fuchsia],[2,light_lavender],[1,light_magenta]]).
contains(muted_yellow,[[4,striped_plum],[2,faded_beige],[1,dull_salmon],[5,bright_red]]).
contains(striped_brown,[[3,bright_red],[3,shiny_violet]]).
contains(posh_white,[[2,mirrored_violet],[4,muted_silver]]).
contains(posh_lavender,[[5,light_crimson],[5,pale_silver],[2,shiny_green],[4,mirrored_silver]]).
contains(plaid_beige,[[3,mirrored_silver]]).
contains(dull_silver,[[1,dotted_silver],[1,drab_salmon]]).
contains(dark_violet,[[3,dotted_green],[1,muted_aqua],[4,bright_chartreuse]]).
contains(dotted_maroon,[[3,clear_red],[4,drab_blue],[4,vibrant_gray]]).
contains(dim_green,[[4,dotted_silver]]).
contains(vibrant_fuchsia,[[5,shiny_violet],[1,dim_violet],[5,dotted_beige]]).
contains(muted_salmon,[[5,dim_white]]).
contains(drab_orange,[[5,dark_teal]]).
contains(vibrant_violet,[[4,posh_cyan],[4,mirrored_brown],[5,dark_beige]]).
contains(bright_crimson,[[1,plaid_fuchsia],[2,drab_black]]).
contains(muted_plum,[[4,striped_brown],[4,dull_green],[4,mirrored_beige]]).
contains(plaid_violet,[[4,dotted_indigo]]).
contains(wavy_yellow,[[3,plaid_lime],[2,mirrored_orange]]).
contains(faded_teal,[[2,clear_plum],[2,posh_purple],[3,muted_plum],[2,dim_tomato]]).
contains(vibrant_brown,[[1,light_tan],[1,light_lime]]).
contains(vibrant_turquoise,[[2,clear_bronze],[2,striped_gray],[2,pale_green],[5,vibrant_indigo]]).
contains(dark_black,[[3,mirrored_gray]]).
contains(muted_orange,[[2,dull_orange]]).
contains(shiny_aqua,[[1,posh_turquoise]]).
contains(posh_fuchsia,[[2,shiny_fuchsia],[5,light_gold]]).
contains(light_plum,[[1,pale_teal],[4,plaid_maroon],[3,drab_maroon]]).
contains(posh_plum,[[4,muted_magenta]]).
contains(plaid_teal,[[1,muted_gray],[3,clear_bronze],[5,pale_tomato]]).
contains(pale_aqua,[[4,posh_turquoise],[5,light_chartreuse],[1,pale_white],[5,light_gold]]).
contains(bright_tomato,[[4,bright_yellow],[5,dark_red],[1,shiny_orange],[1,dim_teal]]).
contains(light_teal,[]).
contains(dark_olive,[[1,drab_gray],[2,striped_teal]]).
contains(dotted_tan,[[4,shiny_salmon],[2,light_black],[5,bright_red]]).
contains(light_cyan,[[1,clear_beige],[4,plaid_orange],[5,wavy_lavender]]).
contains(dark_indigo,[[5,mirrored_orange],[3,posh_brown]]).
contains(clear_fuchsia,[[1,dark_red],[2,posh_black]]).
contains(dotted_salmon,[[5,pale_gray]]).
contains(mirrored_turquoise,[[1,light_aqua]]).
contains(plaid_olive,[[2,dull_silver],[2,light_black]]).
contains(posh_crimson,[[4,drab_black],[4,dim_teal],[5,light_cyan],[3,dark_teal]]).
contains(dull_lime,[]).
contains(drab_chartreuse,[[1,faded_tan]]).
contains(faded_gray,[[5,dark_crimson],[3,light_lavender],[5,dim_silver]]).
contains(wavy_indigo,[[3,muted_chartreuse],[2,dim_green],[3,light_fuchsia],[3,shiny_white]]).
contains(light_tan,[[1,light_olive],[1,dim_cyan],[5,plaid_orange]]).
contains(light_fuchsia,[[2,shiny_indigo],[5,wavy_coral],[2,wavy_tomato]]).
contains(dull_yellow,[[4,faded_coral],[3,dim_white],[5,dull_white]]).
contains(drab_magenta,[[4,muted_violet],[5,light_plum],[4,faded_orange]]).
contains(mirrored_gray,[[2,wavy_cyan],[1,drab_teal],[1,clear_red],[5,bright_lavender]]).
contains(dull_coral,[[1,bright_yellow],[5,dull_violet],[5,dark_orange],[2,bright_green]]).
contains(mirrored_olive,[[1,drab_plum],[3,plaid_orange]]).
contains(muted_olive,[[5,shiny_gold],[2,shiny_aqua],[5,wavy_chartreuse],[4,wavy_lavender]]).
contains(clear_gold,[[3,bright_purple],[3,light_cyan],[5,wavy_tomato]]).
contains(plaid_green,[[4,shiny_yellow],[2,light_salmon],[2,light_silver],[5,dim_purple]]).
contains(posh_red,[[5,dark_violet]]).
contains(muted_purple,[[3,drab_salmon]]).
contains(vibrant_aqua,[[5,clear_beige],[3,vibrant_silver],[1,faded_olive]]).
contains(striped_indigo,[[3,plaid_brown],[4,light_aqua],[3,pale_tomato]]).
contains(wavy_tan,[[2,faded_indigo],[1,vibrant_chartreuse],[5,drab_beige],[4,drab_gold]]).
contains(shiny_gold,[[5,wavy_chartreuse]]).
contains(wavy_purple,[[5,faded_maroon],[4,pale_magenta]]).
contains(mirrored_indigo,[[2,plaid_black],[5,dark_teal],[2,dull_indigo]]).
contains(plaid_crimson,[[5,dotted_green],[2,dull_white]]).
contains(dark_aqua,[[1,wavy_coral],[1,plaid_crimson]]).
contains(shiny_fuchsia,[[1,dark_olive],[4,wavy_silver],[2,bright_turquoise],[1,dull_white]]).
contains(striped_orange,[[4,dotted_green],[1,mirrored_coral],[5,dull_indigo]]).
contains(drab_purple,[[1,posh_orange],[1,bright_blue]]).
contains(dull_orange,[[3,dim_indigo],[3,pale_orange]]).
contains(pale_plum,[[2,light_yellow]]).
contains(pale_cyan,[[4,drab_salmon],[3,dull_magenta],[1,clear_plum],[1,faded_tomato]]).
contains(dotted_indigo,[[1,mirrored_beige],[1,drab_black],[4,shiny_aqua]]).
contains(shiny_lavender,[[1,muted_beige],[5,bright_cyan],[2,dull_green]]).
contains(drab_lime,[[5,drab_black],[4,dotted_salmon]]).
contains(mirrored_bronze,[[3,dim_bronze],[3,striped_tan],[4,clear_maroon],[4,dotted_coral]]).
contains(shiny_brown,[[4,striped_gold],[1,vibrant_silver],[3,shiny_gold]]).
contains(striped_chartreuse,[[5,vibrant_gray],[1,dark_cyan]]).
contains(muted_black,[[4,plaid_indigo]]).
contains(muted_aqua,[[1,pale_red],[5,pale_aqua]]).
contains(bright_maroon,[[2,drab_black],[1,clear_violet],[1,dotted_lavender],[1,mirrored_turquoise]]).
contains(vibrant_chartreuse,[[5,pale_silver]]).
contains(dull_purple,[[2,mirrored_chartreuse]]).
contains(clear_brown,[[2,light_coral],[4,plaid_cyan],[3,dim_brown]]).
contains(shiny_teal,[[5,drab_black],[2,shiny_silver],[3,muted_purple]]).
contains(dull_aqua,[[5,dotted_lime],[4,mirrored_lime]]).
contains(wavy_green,[[1,striped_brown],[2,striped_turquoise],[4,dull_silver],[3,drab_white]]).
contains(clear_gray,[[5,pale_tan],[4,posh_tomato],[3,dark_brown],[1,striped_violet]]).
contains(bright_cyan,[[5,drab_salmon],[5,light_crimson]]).
contains(clear_silver,[[4,mirrored_turquoise],[4,posh_orange],[3,light_gold],[4,clear_green]]).
contains(pale_purple,[[5,dotted_beige],[5,posh_orange]]).
contains(striped_tomato,[[1,dotted_green],[4,dark_turquoise]]).
contains(muted_tan,[[2,faded_green],[3,dim_cyan]]).
contains(dark_coral,[[2,dim_chartreuse],[1,striped_plum]]).
contains(shiny_white,[[2,posh_orange]]).
contains(dim_olive,[[1,faded_teal],[4,pale_lime],[3,dim_teal]]).
contains(faded_black,[[4,pale_cyan],[3,dull_gray],[5,light_teal],[4,shiny_bronze]]).
contains(light_indigo,[[3,dim_cyan],[1,shiny_silver],[5,dull_lavender]]).
contains(dim_coral,[[2,striped_silver],[4,dim_tomato]]).
contains(plaid_tan,[[2,mirrored_turquoise],[4,dim_beige],[5,shiny_lavender],[4,dim_bronze]]).
contains(striped_plum,[[2,wavy_lavender],[1,drab_white]]).
contains(faded_white,[[1,dim_coral]]).
contains(dotted_lime,[[2,muted_gold],[5,shiny_violet],[5,plaid_violet],[1,wavy_bronze]]).
contains(dotted_violet,[[1,posh_orange],[2,plaid_fuchsia]]).
contains(dull_gold,[[5,vibrant_crimson],[1,drab_bronze],[3,dotted_tan]]).
contains(bright_red,[[4,pale_white],[4,light_chartreuse],[3,clear_beige],[5,dotted_green]]).
contains(wavy_cyan,[[5,dotted_chartreuse],[1,wavy_violet],[1,posh_coral],[5,dotted_bronze]]).
contains(faded_fuchsia,[[3,posh_maroon],[4,clear_plum],[3,drab_lime]]).
contains(dim_violet,[]).
contains(striped_bronze,[[2,dim_orange],[1,dark_orange],[1,dark_salmon],[4,faded_teal]]).
contains(drab_olive,[[2,striped_violet],[2,pale_beige]]).
contains(muted_red,[[5,pale_aqua],[1,wavy_cyan],[4,clear_white],[1,drab_red]]).
contains(shiny_blue,[[5,plaid_aqua],[2,drab_salmon],[5,pale_tan],[4,vibrant_cyan]]).
contains(dotted_olive,[[5,dark_brown]]).
contains(shiny_silver,[[3,light_gold],[5,bright_crimson],[4,dark_turquoise]]).
contains(dark_beige,[[1,mirrored_red],[3,dark_salmon],[5,striped_silver],[3,plaid_orange]]).
contains(plaid_red,[[2,wavy_fuchsia],[2,shiny_turquoise],[1,shiny_coral]]).
contains(mirrored_beige,[[1,plaid_crimson],[4,dotted_beige],[2,clear_beige],[2,muted_blue]]).
contains(dim_plum,[[4,striped_cyan],[5,shiny_beige],[2,vibrant_olive],[4,light_maroon]]).
contains(dotted_beige,[[3,shiny_violet],[5,dim_violet],[5,dull_white],[2,plaid_fuchsia]]).
contains(pale_beige,[[2,light_aqua]]).
contains(dim_gray,[[4,dotted_indigo],[4,dim_coral]]).
contains(light_purple,[[5,shiny_brown],[2,drab_violet],[1,striped_tomato]]).
contains(dark_salmon,[[1,dim_green],[5,dim_tan]]).
contains(mirrored_lime,[[5,light_gold],[5,drab_tan]]).
contains(clear_blue,[[3,drab_tomato],[3,pale_olive]]).
contains(plaid_lavender,[[5,shiny_indigo],[3,muted_crimson],[5,mirrored_lime]]).
contains(vibrant_tomato,[[3,drab_salmon],[5,faded_purple],[1,faded_bronze],[4,bright_fuchsia]]).
contains(posh_turquoise,[[1,dim_chartreuse]]).
contains(clear_turquoise,[[4,muted_indigo],[1,dark_maroon],[4,dull_coral]]).
contains(drab_crimson,[[1,plaid_turquoise],[2,faded_salmon]]).
contains(dark_brown,[]).
contains(faded_tomato,[[2,light_cyan],[1,light_maroon]]).
contains(clear_plum,[[2,drab_lavender]]).
contains(bright_white,[[2,dim_tan],[1,faded_orange],[1,dim_aqua]]).
contains(shiny_green,[[3,dotted_coral],[1,mirrored_white],[3,shiny_gray]]).
contains(clear_olive,[[3,mirrored_teal]]).
contains(striped_red,[[1,pale_green],[4,light_maroon]]).
contains(dull_tomato,[[3,mirrored_white],[4,posh_bronze]]).
contains(light_silver,[[1,mirrored_plum],[2,dim_teal]]).
contains(striped_teal,[[4,light_bronze]]).
contains(mirrored_tan,[[5,light_gold],[2,posh_brown]]).
contains(clear_purple,[[5,clear_magenta],[2,pale_tomato],[2,light_black]]).
contains(faded_green,[[5,light_green],[5,plaid_bronze]]).
contains(shiny_red,[[3,dark_white],[2,posh_green],[2,shiny_indigo]]).
contains(muted_white,[[4,dotted_coral],[5,wavy_blue]]).
contains(dim_crimson,[[3,wavy_blue],[2,pale_gray]]).
contains(striped_lavender,[[2,dark_blue],[2,pale_aqua],[5,striped_turquoise],[3,dark_coral]]).
contains(wavy_gray,[[2,muted_gray],[1,pale_silver],[5,muted_blue],[5,pale_tomato]]).
contains(mirrored_silver,[[2,mirrored_black],[5,mirrored_plum],[5,striped_silver],[3,dotted_green]]).
contains(light_crimson,[[4,faded_maroon],[4,dim_chartreuse],[5,dotted_violet]]).
contains(shiny_coral,[[4,shiny_silver],[3,posh_yellow],[5,plaid_blue],[3,shiny_aqua]]).
contains(pale_red,[[4,drab_white],[1,dotted_silver],[4,drab_salmon],[3,dull_green]]).
contains(posh_maroon,[[1,dim_green]]).
contains(posh_gold,[[1,pale_green],[5,striped_silver]]).
contains(light_blue,[[2,dotted_silver],[1,muted_beige]]).
contains(pale_lavender,[[5,vibrant_orange],[2,dull_chartreuse]]).
contains(faded_gold,[[2,shiny_gray]]).
contains(bright_orange,[[3,posh_teal],[5,wavy_green],[1,bright_chartreuse],[5,dark_white]]).
contains(mirrored_violet,[[2,pale_white],[5,dark_brown],[5,bright_blue]]).
contains(dim_white,[[4,clear_green]]).
contains(light_aqua,[]).
contains(dull_chartreuse,[[5,striped_gold]]).
contains(clear_salmon,[[5,pale_salmon]]).
contains(bright_olive,[[1,posh_blue]]).
contains(bright_lavender,[[2,pale_lime]]).
contains(pale_turquoise,[[3,muted_chartreuse]]).
contains(vibrant_white,[[5,light_red]]).
contains(dotted_silver,[[1,dark_brown],[5,dark_turquoise],[4,dim_violet]]).
contains(dull_green,[[2,light_teal],[5,drab_black]]).
contains(wavy_plum,[[4,pale_indigo],[3,plaid_yellow],[1,wavy_green],[4,muted_green]]).
contains(vibrant_yellow,[[2,bright_beige],[2,dim_brown],[3,dotted_teal]]).
contains(faded_beige,[[3,dim_brown],[4,clear_gold]]).
contains(dotted_purple,[[4,shiny_white]]).
contains(mirrored_green,[[5,dark_red],[4,drab_violet],[3,bright_lavender]]).
contains(shiny_tomato,[[3,striped_lavender]]).
contains(bright_silver,[[1,dotted_magenta],[3,dim_green],[1,muted_coral],[4,shiny_teal]]).
contains(plaid_maroon,[[5,dim_brown]]).
contains(dim_salmon,[[4,pale_olive],[5,dark_crimson]]).
contains(dark_gold,[[3,dark_orange],[3,bright_fuchsia],[1,dull_salmon],[5,dark_blue]]).
contains(striped_cyan,[[3,plaid_blue],[1,dark_orange],[5,clear_violet]]).
contains(dark_gray,[[5,light_orange]]).
contains(posh_gray,[[1,plaid_maroon],[4,drab_gold],[1,muted_gold],[4,light_bronze]]).
contains(pale_gold,[[4,clear_orange],[5,dim_orange]]).
contains(pale_teal,[[1,posh_teal],[5,pale_red]]).
contains(vibrant_lavender,[[5,plaid_silver],[3,clear_orange],[2,posh_silver],[1,wavy_violet]]).
contains(dim_black,[[2,dark_plum],[2,plaid_turquoise],[3,dull_salmon],[2,clear_orange]]).
contains(dark_white,[[2,vibrant_fuchsia]]).
contains(dark_red,[[3,shiny_violet],[5,vibrant_fuchsia],[1,pale_crimson]]).
contains(striped_silver,[[2,posh_purple],[4,dark_white]]).
contains(striped_turquoise,[[1,bright_brown],[2,dotted_green]]).
contains(wavy_salmon,[[5,light_teal]]).
contains(muted_turquoise,[[1,bright_gray],[2,plaid_orange],[5,muted_blue],[2,dotted_olive]]).
contains(wavy_black,[[2,mirrored_black],[2,striped_plum],[1,dull_lime],[4,posh_teal]]).
contains(striped_tan,[[5,pale_green]]).
contains(dark_turquoise,[[5,shiny_violet],[3,dark_brown]]).
contains(plaid_black,[[5,plaid_crimson],[2,dim_turquoise],[4,dotted_black]]).
contains(light_turquoise,[[4,plaid_chartreuse],[4,dull_violet]]).
contains(plaid_gray,[[1,light_yellow],[4,striped_lavender],[4,wavy_chartreuse],[3,dotted_salmon]]).
contains(drab_black,[]).
contains(plaid_cyan,[[1,dim_tan],[2,plaid_gold],[1,drab_gray]]).
contains(bright_tan,[[1,plaid_olive],[3,mirrored_black]]).
contains(faded_brown,[[2,dotted_tomato]]).
contains(dotted_fuchsia,[[5,drab_silver]]).
contains(drab_white,[[5,shiny_violet]]).
contains(posh_salmon,[[3,striped_turquoise]]).
contains(dull_maroon,[[2,faded_indigo]]).
contains(bright_bronze,[[1,muted_blue],[5,dark_chartreuse],[2,wavy_purple],[3,vibrant_violet]]).
contains(plaid_bronze,[[1,dark_brown]]).
contains(dark_lavender,[[3,dim_yellow],[4,drab_red],[2,bright_turquoise],[4,shiny_black]]).
contains(wavy_silver,[[1,light_yellow],[2,pale_red]]).
contains(pale_tan,[[5,dull_orange],[5,dotted_olive],[2,vibrant_purple],[4,dull_tan]]).
contains(pale_orange,[[3,light_teal],[1,dim_maroon]]).
contains(shiny_indigo,[[3,drab_maroon],[2,dotted_indigo],[1,bright_purple],[2,striped_brown]]).
contains(muted_fuchsia,[[4,posh_crimson],[3,clear_beige]]).
contains(plaid_plum,[[1,clear_silver],[4,light_cyan],[1,vibrant_gray],[5,drab_purple]]).
contains(faded_violet,[[3,dotted_beige],[3,muted_aqua]]).
contains(dotted_plum,[[4,plaid_brown],[5,wavy_green],[3,dark_cyan],[2,pale_red]]).
contains(vibrant_tan,[[4,clear_gray]]).
contains(drab_silver,[[3,dull_chartreuse]]).
contains(shiny_turquoise,[[4,dark_olive]]).
contains(dark_silver,[[2,dotted_black]]).
contains(striped_beige,[[5,striped_magenta]]).
contains(dotted_orange,[[1,light_aqua],[4,posh_turquoise]]).
contains(shiny_magenta,[[3,drab_salmon],[5,mirrored_orange]]).
contains(posh_magenta,[[3,plaid_fuchsia],[4,dim_maroon]]).
contains(clear_bronze,[[1,wavy_fuchsia],[2,vibrant_black]]).
contains(dull_violet,[[1,muted_indigo],[2,posh_green],[4,striped_white],[1,clear_red]]).
contains(posh_lime,[[5,vibrant_cyan]]).
contains(pale_silver,[[2,dark_crimson],[1,light_salmon],[1,clear_brown]]).
contains(posh_yellow,[[1,dim_white],[2,pale_crimson]]).
contains(vibrant_bronze,[[4,faded_gray],[1,dim_gray],[2,posh_cyan],[4,plaid_lavender]]).
contains(dull_beige,[[4,wavy_fuchsia],[4,plaid_crimson],[2,dark_blue],[1,wavy_silver]]).
contains(dull_brown,[[4,pale_turquoise],[4,clear_tan]]).
contains(faded_turquoise,[[5,plaid_gold],[4,wavy_chartreuse]]).
contains(dark_yellow,[[1,wavy_lavender],[5,dark_coral]]).
contains(dotted_gray,[[4,posh_purple],[5,wavy_lavender],[5,shiny_green],[5,plaid_white]]).
contains(dim_aqua,[[1,dull_lime]]).
contains(posh_violet,[[1,mirrored_tomato],[3,posh_cyan]]).
contains(shiny_gray,[[3,clear_green],[1,wavy_bronze],[4,dark_turquoise],[3,pale_white]]).
contains(drab_red,[[2,mirrored_violet],[3,dotted_orange],[5,dark_lime],[4,bright_purple]]).
contains(striped_magenta,[[3,striped_brown]]).
contains(dull_magenta,[[4,dim_tomato],[3,muted_beige],[5,clear_violet]]).
contains(clear_maroon,[[4,plaid_lime]]).
contains(posh_silver,[[3,mirrored_red]]).
contains(dark_crimson,[[2,mirrored_violet]]).
contains(pale_maroon,[[2,shiny_black]]).
contains(dark_magenta,[[1,dark_green],[4,light_plum]]).
contains(bright_lime,[[1,pale_indigo],[3,dim_yellow],[2,drab_maroon],[4,light_plum]]).
contains(dark_orange,[[1,wavy_lavender],[1,dotted_orange],[2,light_crimson],[3,light_yellow]]).
contains(wavy_lime,[[4,clear_blue],[2,muted_brown],[2,mirrored_violet],[2,dotted_lavender]]).
contains(dotted_lavender,[[1,posh_teal],[5,dark_red],[1,pale_gray]]).
contains(muted_brown,[[1,dark_white],[2,dull_maroon],[1,faded_maroon]]).
contains(dim_yellow,[[5,dark_white]]).
contains(faded_tan,[[4,light_coral],[4,light_yellow]]).
contains(faded_crimson,[[3,plaid_fuchsia],[5,plaid_orange]]).
contains(pale_salmon,[[5,pale_red],[4,dotted_olive],[3,plaid_magenta]]).
contains(dim_bronze,[[4,muted_plum],[3,light_cyan],[3,dark_coral]]).
contains(bright_teal,[[2,vibrant_violet],[4,striped_bronze],[1,striped_violet],[2,dark_gray]]).
contains(pale_bronze,[[2,plaid_brown],[1,plaid_white]]).
contains(vibrant_plum,[[2,drab_tan],[2,plaid_yellow],[3,faded_fuchsia]]).
contains(dotted_teal,[[5,faded_coral],[5,faded_indigo],[1,posh_violet],[3,pale_indigo]]).
contains(plaid_salmon,[[2,dark_lavender],[3,posh_bronze],[4,light_coral],[1,posh_orange]]).
contains(dim_red,[[3,light_violet]]).
contains(drab_gold,[[4,wavy_silver],[5,light_bronze]]).
contains(shiny_violet,[]).
contains(mirrored_maroon,[[1,drab_yellow],[5,wavy_beige]]).
contains(dotted_aqua,[[4,muted_plum]]).
contains(faded_salmon,[[4,mirrored_olive],[5,dim_lavender]]).
contains(light_violet,[[2,wavy_salmon]]).
contains(plaid_brown,[[5,faded_indigo]]).
contains(mirrored_coral,[[4,pale_gray]]).
contains(muted_lavender,[[1,posh_beige],[2,clear_silver],[1,dotted_bronze]]).
contains(bright_turquoise,[[2,striped_black],[3,dull_maroon]]).
contains(vibrant_gold,[[5,bright_purple],[1,bright_red]]).
contains(muted_magenta,[[1,clear_violet],[5,muted_lavender],[4,faded_aqua]]).
contains(faded_silver,[[4,posh_brown],[2,mirrored_silver]]).
contains(dim_teal,[[2,dim_violet],[1,dark_white],[2,dotted_black]]).
contains(striped_maroon,[[5,shiny_white]]).
contains(dark_maroon,[[2,plaid_silver],[1,dull_red],[2,shiny_coral],[5,bright_white]]).
contains(clear_crimson,[[4,muted_salmon],[5,clear_green],[1,light_blue],[5,posh_magenta]]).
contains(dotted_yellow,[[3,vibrant_coral]]).
contains(light_tomato,[[4,dim_chartreuse],[4,light_gold],[5,dark_white]]).
contains(shiny_purple,[[3,dark_turquoise]]).
contains(bright_green,[[1,light_chartreuse]]).
contains(mirrored_yellow,[[4,striped_white]]).
contains(light_lavender,[[1,wavy_crimson],[3,dim_yellow],[1,plaid_olive],[5,wavy_white]]).
contains(muted_crimson,[[2,dark_beige],[1,dull_green]]).
contains(muted_blue,[[3,shiny_aqua],[5,dark_turquoise],[1,dotted_silver]]).
contains(striped_coral,[[2,dark_red],[1,drab_blue],[2,light_aqua],[1,striped_lavender]]).
contains(light_brown,[[4,plaid_yellow]]).
contains(clear_aqua,[[1,plaid_olive],[1,plaid_gold],[1,muted_tan]]).
contains(dotted_gold,[[2,dark_white]]).
contains(plaid_blue,[[5,dotted_coral],[3,muted_blue]]).
contains(mirrored_cyan,[[3,dark_white],[1,striped_turquoise],[3,light_coral]]).
contains(faded_red,[[3,clear_tan],[5,striped_brown],[3,shiny_cyan]]).
contains(clear_lime,[[4,clear_silver]]).
contains(dim_lime,[[2,light_teal],[1,posh_turquoise],[3,dotted_silver],[1,drab_lavender]]).
contains(dull_teal,[[1,light_maroon],[4,bright_coral]]).
contains(light_gray,[[5,mirrored_lime],[3,light_violet],[1,muted_olive],[4,striped_brown]]).
contains(dotted_white,[[3,wavy_white],[1,dotted_beige],[5,clear_green]]).
contains(shiny_crimson,[[3,pale_salmon],[3,dark_lime],[4,dull_blue],[1,vibrant_chartreuse]]).
contains(dim_brown,[[5,mirrored_beige],[5,light_orange],[2,faded_crimson]]).
contains(dim_blue,[[5,pale_gray]]).
contains(striped_black,[[2,vibrant_purple],[4,vibrant_salmon],[2,clear_gold],[3,shiny_yellow]]).
contains(striped_fuchsia,[[3,plaid_fuchsia],[4,posh_teal],[5,drab_tomato],[3,dim_turquoise]]).
contains(shiny_black,[[2,striped_tomato]]).
contains(vibrant_maroon,[[5,bright_aqua],[1,posh_white],[1,pale_silver],[2,muted_tan]]).
contains(posh_coral,[[2,mirrored_violet],[2,mirrored_beige],[4,striped_tomato],[2,drab_white]]).
contains(wavy_chartreuse,[[5,muted_blue],[1,bright_crimson],[1,pale_gray],[1,shiny_silver]]).
contains(bright_chartreuse,[[5,striped_brown]]).
contains(bright_gray,[[3,drab_gray],[4,plaid_cyan],[1,drab_maroon]]).
contains(dark_lime,[[4,clear_green],[4,dotted_white]]).
contains(faded_maroon,[[5,shiny_gold],[4,dotted_green],[2,striped_brown]]).
contains(dim_silver,[[5,muted_tomato],[5,mirrored_violet]]).
contains(faded_chartreuse,[[2,pale_gray],[3,striped_cyan]]).
contains(posh_beige,[[3,faded_blue]]).
contains(striped_aqua,[[5,bright_gray],[4,shiny_aqua],[3,shiny_gray]]).
contains(dull_tan,[[2,dotted_green],[3,light_crimson],[3,mirrored_fuchsia],[5,shiny_cyan]]).
contains(dark_green,[[2,drab_yellow]]).
contains(wavy_fuchsia,[[2,wavy_gray],[1,faded_fuchsia],[5,bright_maroon]]).
contains(vibrant_indigo,[[5,dotted_tomato],[4,light_coral],[1,dark_silver]]).
contains(drab_indigo,[[5,pale_coral]]).
contains(faded_indigo,[[5,vibrant_fuchsia],[1,wavy_coral],[3,striped_teal]]).
contains(pale_violet,[[3,pale_lime],[2,posh_indigo],[5,muted_blue],[2,plaid_cyan]]).
contains(drab_blue,[[3,dull_silver],[2,dotted_beige],[1,muted_aqua],[3,dotted_orange]]).
contains(dull_crimson,[[2,dim_brown],[1,mirrored_black]]).
contains(mirrored_lavender,[[2,posh_chartreuse],[1,vibrant_blue],[5,dull_magenta]]).
contains(light_olive,[[5,dotted_silver],[5,dim_white],[5,pale_teal]]).
contains(vibrant_blue,[[1,dark_fuchsia],[5,dim_teal]]).
contains(dim_chartreuse,[]).
contains(bright_black,[[1,dull_lavender],[3,dark_teal],[2,plaid_blue],[5,dark_white]]).
contains(dark_cyan,[[5,light_beige],[5,bright_orange]]).
contains(light_yellow,[[5,striped_silver],[2,dark_brown],[2,dotted_salmon],[4,dim_violet]]).
contains(dotted_bronze,[[5,dim_blue],[2,dark_chartreuse]]).
contains(faded_yellow,[[1,faded_fuchsia],[4,dark_brown],[1,muted_salmon]]).
contains(dull_fuchsia,[[1,bright_turquoise],[1,drab_green]]).
contains(faded_blue,[[5,dull_chartreuse],[1,shiny_violet]]).
contains(striped_gold,[[2,dull_silver],[4,dotted_black]]).
contains(mirrored_black,[[1,wavy_tomato],[3,posh_violet],[4,vibrant_crimson],[1,dull_lime]]).
contains(posh_tan,[[2,plaid_olive],[5,dotted_white]]).
contains(vibrant_black,[[1,light_chartreuse],[2,dark_orange]]).
contains(dim_indigo,[[1,plaid_crimson]]).
contains(mirrored_red,[[4,faded_maroon]]).
contains(vibrant_beige,[[5,faded_teal],[5,shiny_coral],[4,drab_teal]]).
contains(drab_gray,[[4,light_teal],[1,dull_white]]).
contains(pale_blue,[[1,posh_purple],[4,light_cyan]]).
contains(posh_indigo,[[4,dim_gray],[2,striped_maroon],[4,drab_white],[3,light_tomato]]).
contains(dim_maroon,[[3,pale_white]]).
contains(faded_aqua,[[2,drab_white],[3,faded_purple],[4,striped_maroon]]).
contains(plaid_aqua,[[1,striped_turquoise],[4,light_bronze],[3,pale_chartreuse]]).
contains(dull_lavender,[[5,striped_plum],[1,dotted_white],[2,dotted_salmon],[5,dull_silver]]).
contains(light_magenta,[[2,drab_violet],[5,drab_coral],[2,vibrant_lavender],[3,dull_olive]]).
contains(faded_lime,[[3,mirrored_coral],[2,wavy_lavender],[3,light_yellow],[1,shiny_silver]]).
contains(wavy_white,[[4,drab_white]]).
contains(clear_indigo,[[3,dim_cyan]]).
contains(plaid_turquoise,[[4,drab_white],[3,dark_teal],[2,plaid_fuchsia]]).
contains(plaid_tomato,[[3,drab_violet],[5,striped_salmon]]).
contains(bright_beige,[[5,shiny_black],[5,posh_salmon],[4,striped_bronze],[3,pale_plum]]).
contains(vibrant_red,[[4,pale_fuchsia]]).
contains(posh_green,[[1,drab_red]]).
contains(faded_plum,[[5,plaid_chartreuse],[5,bright_bronze],[4,dark_blue],[3,clear_bronze]]).
contains(dim_turquoise,[[3,light_chartreuse]]).
contains(clear_red,[[1,drab_blue],[5,striped_fuchsia],[5,striped_brown],[3,clear_silver]]).
contains(pale_gray,[[1,dull_green],[2,dotted_orange],[2,dark_turquoise]]).
contains(plaid_purple,[[1,dim_cyan],[4,striped_lime],[3,drab_violet]]).
contains(clear_teal,[[2,dull_cyan],[1,wavy_cyan],[2,light_blue]]).
contains(mirrored_brown,[[5,mirrored_red]]).
contains(light_bronze,[[1,wavy_white]]).
contains(muted_gray,[[5,faded_lime],[1,pale_beige],[1,shiny_indigo],[1,faded_tan]]).
contains(striped_salmon,[[5,dim_teal],[5,dotted_silver],[5,dim_gray]]).
contains(bright_indigo,[[3,drab_beige],[1,shiny_red],[4,vibrant_silver],[4,clear_plum]]).
contains(pale_coral,[[5,wavy_plum],[2,clear_beige]]).
contains(faded_olive,[[2,bright_crimson],[5,dotted_green],[5,dull_bronze],[2,posh_turquoise]]).
contains(wavy_maroon,[[5,mirrored_fuchsia],[5,dim_olive]]).
contains(plaid_indigo,[[5,posh_magenta],[1,dim_bronze],[1,light_blue]]).
contains(posh_aqua,[[5,clear_beige],[3,dark_lime]]).
contains(faded_cyan,[[1,drab_tomato],[4,posh_crimson],[5,pale_chartreuse],[3,faded_tan]]).
contains(plaid_yellow,[[3,wavy_cyan],[3,striped_black]]).
contains(faded_magenta,[[4,bright_coral]]).
contains(dull_cyan,[[4,mirrored_magenta],[3,clear_chartreuse]]).
contains(vibrant_coral,[[2,dotted_aqua],[1,bright_cyan]]).
contains(mirrored_gold,[[2,shiny_purple]]).
contains(mirrored_purple,[[3,dark_beige]]).
contains(pale_yellow,[[5,plaid_coral],[3,wavy_silver],[1,mirrored_salmon],[3,light_lime]]).
contains(dark_tan,[[1,light_yellow],[5,plaid_turquoise],[4,shiny_gold]]).
contains(faded_bronze,[[5,striped_gold],[1,posh_teal]]).
contains(light_black,[[2,shiny_black],[2,mirrored_coral]]).
contains(vibrant_gray,[[5,dark_teal],[3,muted_aqua],[4,shiny_violet],[5,dark_bronze]]).
contains(wavy_beige,[[2,pale_maroon]]).
contains(muted_silver,[[4,plaid_orange],[1,shiny_chartreuse]]).
contains(plaid_magenta,[[1,dotted_tan],[3,striped_fuchsia],[5,light_olive]]).
contains(drab_fuchsia,[[5,dark_violet],[1,shiny_gold],[3,pale_cyan]]).
contains(shiny_chartreuse,[[5,dotted_violet]]).
contains(pale_crimson,[[3,pale_aqua]]).
contains(dull_white,[]).
contains(pale_green,[[4,bright_green],[2,dull_lime],[1,striped_lime]]).
contains(muted_bronze,[[5,bright_tomato],[5,light_red],[2,shiny_yellow],[2,dim_teal]]).
contains(mirrored_aqua,[[3,dim_tomato],[1,mirrored_crimson],[1,wavy_silver]]).
contains(vibrant_magenta,[[2,dark_lime]]).
