VARIABLE FACTOR
VARIABLE RESULT1
VARIABLE RESULT1-DEC
VARIABLE RESULT2
VARIABLE RESULT2-DEC
VARIABLE NBITEMS


0 RESULT1-DEC !
0 RESULT2-DEC !
0 RESULT1 !
0 RESULT2 !

: COMPUTE1
  s" data.fs" INCLUDED
  DEPTH NBITEMS !
  0
  BEGIN
  SWAP
  FACTOR @ /
  10 MOD
  +
  DEPTH 1 = UNTIL
  NBITEMS @ 2 /
  >= IF 1 ELSE 0 THEN
  FACTOR @ *
  RESULT1 @ + RESULT1 !
  FACTOR @ 10 / FACTOR !
  FACTOR @ 0= IF RESULT1 @ ELSE RECURSE THEN
  ;

: CONVERT-TO-DEC1
  1 FACTOR !
  BEGIN
  RESULT1 @ 10 MOD
  FACTOR @ *
  RESULT1-DEC @ + RESULT1-DEC !
  RESULT1 @ 10 / RESULT1 !
  FACTOR @ 2 * FACTOR !
  RESULT1 @ 0= UNTIL
;

: COMPUTE2
  s" data.fs" INCLUDED
  DEPTH NBITEMS !
  0
  BEGIN
  SWAP
  FACTOR @ /
  10 MOD
  +
  DEPTH 1 = UNTIL
  NBITEMS @ 2 /
  \ ONLY CHANGE BETWEEN THE TWO FUNCTIONS
  \ TO GET THE LEAST COMMON
  >= IF 0 ELSE 1 THEN
  FACTOR @ *
  RESULT2 @ + RESULT2 !
  FACTOR @ 10 / FACTOR !
  FACTOR @ 0= IF RESULT2 @ ELSE RECURSE THEN
  ;

: CONVERT-TO-DEC2
  1 FACTOR !
  BEGIN
  RESULT2 @ 10 MOD
  FACTOR @ *
  RESULT2-DEC @ + RESULT2-DEC !
  RESULT2 @ 10 / RESULT2 !
  FACTOR @ 2 * FACTOR !
  RESULT2 @ 0= UNTIL
;

100000000000 FACTOR !
COMPUTE1
CONVERT-TO-DEC1
100000000000 FACTOR !
COMPUTE2
CONVERT-TO-DEC2

RESULT1-DEC @ RESULT2-DEC @ * .
